-- CREATE SEQUENCE SECVENTA_UTILIZATOR 
-- START WITH 1 
-- INCREMENT BY 1; 

CREATE TABLE UTILIZATOR (
  id_utilizator NUMBER PRIMARY KEY,
  nume VARCHAR2(100),
  tip VARCHAR2(50)
);

INSERT INTO UTILIZATOR (id_utilizator, nume, tip) VALUES (1, "Jack", "vocalist");

SELECT * FROM UTILIZATOR;

SELECT NUME FROM UTILIZATOR;

SELECT NUME || " " || TIP AS 'NUME SI TIP' FROM UTILIZATOR;
