-------------
-- CERINTE --
-------------

-- 10. Crearea unei secvențe ce va fi utilizată în inserarea înregistrărilor în tabele (punctul 11). 
-- 11. Crearea tabelelor în SQL și inserarea de date coerente în fiecare dintre acestea (minimum 5 înregistrări în fiecare tabel neasociativ; minimum 10 înregistrări în tabelele asociative; maxim 30 de înregistrări în fiecare tabel). 

------------
-- TABELE --
------------

-- UTILIZATOR (#id_utilizator, id_trupa, id_lista, id_cor, nume) 
-- VOCALIST (#id_utilizator, rol) 
-- INSTRUMENTIST (#id_utilizator) 
-- INSTRUMENT (id_instrumentist, denumire) 
-- LISTA (#id_lista, id_cantare, id_utilizator, nume, data_programare, locatie_programare) 
-- CANTARE (#id_cantare, id_autor, id_lista, id_categorie, nume, gama, bpm) 
-- AUTOR (#id_autor, id_cantare, nume, an_debut) 
-- CATEGORIE (id_cantare, denumire) 
-- COR (#id_cor, id_biserica, numar_membrii, id_utilizator) 
-- BISERICA (#id_biserica, nume) 
-- TRUPA (#id_trupa, nume, an_debut, id_utilizator) 
-- PREMIU (#id_premiu, loc_podium) 
-- COMPETITIE (#id_competitie, nume, locatie) 

-- STERGEM VECHILE TABELE
DROP TABLE UTILIZATOR;
DROP TABLE VOCALIST;
DROP TABLE INSTRUMENTIST;
DROP TABLE INSTRUMENT;
DROP TABLE LISTA;
DROP TABLE CANTARE;
DROP TABLE AUTOR;
DROP TABLE CATEGORIE;
DROP TABLE COR;
DROP TABLE BISERICA;
DROP TABLE TRUPA;
DROP TABLE PREMIU;
DROP TABLE COMPETITIE;

-- ASIDE: STERGEM NISTE TABELE DE TEST (MICA OBSERVATIE: SE PARE CA E CASE-SENSITIVE :) )
-- DROP TABLE test;
-- DROP TABLE TEST;

-- STERGEM VECHEA SECVENTA
DROP SEQUENCE PROGRAM_SEQUENCE;

-- FACEM O NOUA SECVENTA
CREATE SEQUENCE PROGRAM_SEQUENCE 
START WITH 1 INCREMENT BY 1;
 
---------------------
-- ENTITATE: TRUPA --
---------------------

DROP TABLE TRUPA;

CREATE TABLE TRUPA (
    ID_TRUPA NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL,
    AN_DEBUT NUMBER NOT NULL
);

-- ID: 1-10
INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'NOT AN IDOL', 2012);
INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'PROFIDES', 2009);
INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'CIRESARII', 2001);
INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'CRISTOCENTRIC', 2003);
INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'UMAR LA UMAR', 2022);
INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'CALATISE PRAISE', 2010);
INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'ELEVATION WORSHIP', 2023);
INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'BBSO', 20018);
INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'TRIBL', 2024);
INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'HARVEST ARAD', 2025);

SELECT * FROM TRUPA;

----------------------
-- ENTITATE: PREMIU --
----------------------

DROP TABLE PREMIU;

CREATE TABLE PREMIU (
    ID_PREMIU NUMBER PRIMARY KEY,
    LOC_PODIUM NUMBER NOT NULL
);

-- ID: 11-20
INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 3);
INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 2);
INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 3);
INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 1);
INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 1);
INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 2);
INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 2);
INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 2);
INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 3);
INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 1); 

SELECT * FROM PREMIU;

--------------------------
-- ENTITATE: COMPETITIE -- 
--------------------------

DROP TABLE COMPETITIE;

CREATE TABLE COMPETITIE (
    ID_COMPETITIE NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL,
    LOCATIE VARCHAR(44) NOT NULL
);

-- ID: 21-30
INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'VOCEA ROMANIEI', 'BUCURESTI');
INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'ROMANII AU TALENT', 'CLUJ');
INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'TINERI SI CREDINCIOSI', 'BACAU');
INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'X FACTOR', 'MARAMURES');
INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'ROMANII AU TALENT', 'CONSTANTA');
INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'TINERI SI CREDINCIOSI', 'VRANCEA');
INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'X FACTOR', 'ZALAU');
INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'VOCEA ROMANIEI', 'ORADEA');
INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'ROMANII AU TALENT', 'SUCEAVA');
INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'TINERI SI CREDINCIOSI', 'BUCURESTI'); 

SELECT * FROM COMPETITIE;

----------------------------------------------
-- TABEL ASOCIATIV: TRUPA_PREMIU_COMPETITIE --
----------------------------------------------

DROP TABLE TRUPA_PREMIU_COMPETITIE;

CREATE TABLE TRUPA_PREMIU_COMPETITIE (
    ID_TRUPA NUMBER,
    ID_PREMIU NUMBER,
    ID_COMPETITIE NUMBER,
    PRIMARY KEY (ID_TRUPA, ID_PREMIU, ID_COMPETITIE),
    FOREIGN KEY (ID_TRUPA) REFERENCES TRUPA (ID_TRUPA),
    FOREIGN KEY (ID_COMPETITIE) REFERENCES COMPETITIE (ID_COMPETITIE),
    FOREIGN KEY (ID_PREMIU) REFERENCES PREMIU (ID_PREMIU)
);

INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES (1, 11, 21);
INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES (2, 14, 22);
INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES (2, 13, 25);
INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES (2, 18, 22);
INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES (4, 12, 25);
INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES (3, 19, 21);
INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES (4, 17, 22);
INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES (9, 14, 23);
INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES (8, 11, 22);
INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES (4, 18, 27);

SELECT * FROM TRUPA_PREMIU_COMPETITIE;

---------------------
-- ENTITATE: LISTA --
---------------------

DROP TABLE LISTA;

CREATE TABLE LISTA (
    ID_LISTA NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL,
    DATA_PROGRAMARE DATE NOT NULL,
    LOCATIE_PROGRAMARE VARCHAR(44) NOT NULL
);

-- ID: 31-40
INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'REPETITII', TO_DATE('2025-08-11', 'YYYY-MM-DD'), 'VALENII DE MUNTE');
INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'KARAOKE', TO_DATE('2023-01-10', 'YYYY-MM-DD'), 'BISTRITA');
INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'FESTIVAL', TO_DATE('2024-02-23', 'YYYY-MM-DD'), 'CLUJ-NAPOCA');
INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'CONCERT', TO_DATE('2013-05-21', 'YYYY-MM-DD'), 'ARAD');
INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'REPETITII', TO_DATE('2023-03-24', 'YYYY-MM-DD'), 'TIMISOARA');
INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'FESTIVAL', TO_DATE('2022-03-25', 'YYYY-MM-DD'), 'VRANCEA');
INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'CONCERT', TO_DATE('2021-07-20', 'YYYY-MM-DD'), 'ARAD');
INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'CONCERT', TO_DATE('2020-09-13', 'YYYY-MM-DD'), 'VRANCEA');
INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'REPETITII', TO_DATE('2021-01-14', 'YYYY-MM-DD'), 'TULCEA');
INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'FESTIVAL', TO_DATE('2019-02-10', 'YYYY-MM-DD'), 'BACAU'); 

SELECT * FROM LISTA;

------------------------
-- ENTITATE: BISERICA --
------------------------

DROP TABLE BISERICA;

CREATE TABLE BISERICA (
    ID_BISERICA NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL
);

-- ID: 41-50
INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'BETANIA BUCURESTI');
INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'HARVEST ARAD');
INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'PROFIDES BUCURESTI');
INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'BETEL ADJUD');
INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'VESTEA BUNA BUCURESTI');
INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'PROFIDES PARIS');
INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'RENOVATIO');
INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'BISERICA POGORAREA SFANTULUI DUH TITAN'); -- 38 < 44 SE INCADREAZA IN LIMITA :)
INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'BISERICA PROFIDES LUPENI');
INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'BISERICA BETEL COMANESTI'); 

SELECT * FROM BISERICA;

-------------------
-- ENTITATE: COR --
-------------------

DROP TABLE COR;

CREATE TABLE COR (
    ID_COR NUMBER PRIMARY KEY,
    NUMAR_MEMBRII NUMBER NOT NULL,
    ID_BISERICA NUMBER,
    FOREIGN KEY (ID_BISERICA) REFERENCES BISERICA (ID_BISERICA)
);

-- ID: 51-60
INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 800, 41);
INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 100, 49);
INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 400, 42);
INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 80, 41);
INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 40, 48);
INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 1200, 45);
INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 2000, 48);
INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 18, 41);
INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 20000, 49);
INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 82, 50); 

SELECT * FROM COR;

--------------------------
-- ENTITATE: UTILIZATOR --
--------------------------

DROP TABLE UTILIZATOR;

CREATE TABLE UTILIZATOR (
    ID_UTILIZATOR NUMBER PRIMARY KEY,
    NUME VARCHAR2(44) NOT NULL,
    ID_TRUPA NUMBER,
    ID_LISTA NUMBER,
    ID_COR NUMBER,
    FOREIGN KEY (ID_TRUPA) REFERENCES TRUPA(ID_TRUPA),
    FOREIGN KEY (ID_LISTA) REFERENCES LISTA(ID_LISTA),
    FOREIGN KEY (ID_COR) REFERENCES COR(ID_COR)
);

-- ID: 61-70
INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES  (PROGRAM_SEQUENCE.NEXTVAL, 'ANA', 1, 31, 51);
INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES  (PROGRAM_SEQUENCE.NEXTVAL, 'BOGDAN', 7, 34, 54);
INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES  (PROGRAM_SEQUENCE.NEXTVAL, 'MIRCEA', 9, 39, 52);
INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES  (PROGRAM_SEQUENCE.NEXTVAL, 'MARIA', 4, 38, 58);
INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES  (PROGRAM_SEQUENCE.NEXTVAL, 'IOANA', 3, 31, 57);
INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES  (PROGRAM_SEQUENCE.NEXTVAL, 'CARLOS', 9, 31, 55);
INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES  (PROGRAM_SEQUENCE.NEXTVAL, 'TONI', 4, 37, 54);
INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES  (PROGRAM_SEQUENCE.NEXTVAL, 'VLAD', 8, 34, 58);
INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES  (PROGRAM_SEQUENCE.NEXTVAL, 'DIANA', 2, 33, 53);
INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES  (PROGRAM_SEQUENCE.NEXTVAL, 'FLORENTINA', 10, 40, 60); 

SELECT * FROM UTILIZATOR;

------------------------
-- ENTITATE: VOCALIST --
------------------------

DROP TABLE VOCALIST;

CREATE TABLE VOCALIST (
    ID_UTILIZATOR NUMBER,
    FOREIGN KEY (ID_UTILIZATOR) REFERENCES UTILIZATOR (ID_UTILIZATOR),
    ROL VARCHAR(44) NOT NULL
);

INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES (61, 'SOPRANO');
INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES (63, 'BASS');
INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES (68, 'SOPRANO');
INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES (62, 'TENOR');
INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES (63, 'TENOR');
INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES (67, 'BASS');
INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES (61, 'SOPRANO');
INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES (65, 'BASS');
INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES (61, 'BASS');
INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES (70, 'TENOR');

SELECT * FROM VOCALIST;

-----------------------------
-- ENTITATE: INSTRUMENTIST --
-----------------------------

DROP TABLE INSTRUMENTIST;

CREATE TABLE INSTRUMENTIST (
    ID_UTILIZATOR NUMBER,
    FOREIGN KEY (ID_UTILIZATOR) REFERENCES UTILIZATOR (ID_UTILIZATOR)
);

INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES (61);
INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES (62);
INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES (68);
INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES (64);
INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES (68);
INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES (63);
INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES (64);
INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES (61);
INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES (68);
INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES (70);

SELECT * FROM INSTRUMENTIST;

--------------------------
-- ENTITATE: INSTRUMENT --
--------------------------

DROP TABLE INSTRUMENT;

CREATE TABLE INSTRUMENT (
    ID_UTILIZATOR NUMBER,
    DENUMIRE VARCHAR(44) NOT NULL,
    FOREIGN KEY (ID_UTILIZATOR) REFERENCES UTILIZATOR (ID_UTILIZATOR)
);

INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES (61, 'PIAN');
INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES (68, 'CHITARA');
INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES (64, 'MANDOLINA');
INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES (68, 'TOBE');
INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES (63, 'CHITARA ELECTRICA');
INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES (62, 'CHITARA BASS');
INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES (67, 'PIAN');
INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES (62, 'TOBE');
INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES (65, 'MANDOLINA');
INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES (70, 'VIOARA');

SELECT * FROM INSTRUMENT;

-----------------------
-- ENTITATE: CANTARE --
-----------------------

DROP TABLE CANTARE;

CREATE TABLE CANTARE (
    ID_CANTARE NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL,
    GAMA VARCHAR(4) NOT NULL,
    BPM NUMBER NOT NULL,
    ID_LISTA NUMBER,
    FOREIGN KEY (ID_LISTA) REFERENCES LISTA (ID_LISTA)
);

-- ID: 71-80
INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'DOMNUL MINUNILOR', 'G#', 120, 31);
INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'ACEASTA E ZIUA DOMNULUI', 'C', 70, 37);
INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'LUCRURI NOI', 'F', 100, 34);
INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'ANCORA', 'D', 110, 32);
INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'ZI DE ZI', 'G', 120, 39);
INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'DOMNUL STEAGUL MEU', 'D#', 90, 31);
INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'ESTI UNIC', 'A#', 50, 36);
INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'DUMNEZEUL PUTERNIC', 'C', 70, 33);
INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'CREDINCIOS', 'E', 90, 34);
INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'DUMNEZEU E TARIA MEA', 'A#', 40, 40); 

SELECT * FROM CANTARE;

---------------------
-- ENTITATE: AUTOR --
---------------------

DROP TABLE AUTOR;

CREATE TABLE AUTOR (
    ID_AUTOR NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL,
    AN_DEBUT NUMBER NOT NULL,
    ID_CANTARE NUMBER,
    FOREIGN KEY (ID_CANTARE) REFERENCES CANTARE (ID_CANTARE)
);

-- ID: 81-90
INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'SUNNY TRANCA', 2005, 71);
INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'TONI BERBECE', 2008, 79);
INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'VALI TRANCA', 2024, 75);
INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'MIRIAM POPESCU', 2012, 71);
INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'ANCA BAN', 2003, 74);
INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'ALIN JIVAN', 2004, 77);
INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'FLORINA JIVAN', 2004, 72);
INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'SUNNY TRANCA', 2005, 79);
INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'MIRIAM POPESCU', 2012, 73);
INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES (PROGRAM_SEQUENCE.NEXTVAL, 'TONI BERBECE', 2008, 80); 

SELECT * FROM AUTOR;

-------------------------
-- ENTITATE: CATEGORIE --
-------------------------

DROP TABLE CATEGORIE;

CREATE TABLE CATEGORIE (
    ID_CANTARE NUMBER,
    DENUMIRE VARCHAR(44) NOT NULL,
    FOREIGN KEY (ID_CANTARE) REFERENCES CANTARE (ID_CANTARE)
);

INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES (71, 'JAZZ');
INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES (78, 'POP');
INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES (72, 'ROCK');
INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES (73, 'IMN');
INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES (78, 'BISERICEASCA');
INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES (77, 'LAUTAREASCA');
INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES (79, 'POP');
INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES (75, 'ROCK');
INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES (73, 'JAZZ');
INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES (80, 'POP');

SELECT * FROM CATEGORIE;

---------------
-- TEST ZONE --
---------------

SELECT * FROM TRUPA;
SELECT * FROM PREMIU;
SELECT * FROM COMPETITIE;
SELECT * FROM TRUPA_PREMIU_COMPETITIE;
SELECT * FROM LISTA;
SELECT * FROM BISERICA;
SELECT * FROM COR;
SELECT * FROM UTILIZATOR;
SELECT * FROM VOCALIST;
SELECT * FROM INSTRUMENTIST;
SELECT * FROM INSTRUMENT;
SELECT * FROM CANTARE;
SELECT * FROM AUTOR;
SELECT * FROM CATEGORIE;

DROP TABLE TEST;

CREATE TABLE TEST (
    ID_TEST NUMBER,
    NOTA NUMBER
);

INSERT INTO TEST (ID_TEST, NOTA) VALUES (1, 10);

INSERT INTO TEST (ID_TEST, NOTA) VALUES (2, 7);

INSERT INTO TEST (ID_TEST, NOTA) VALUES (3, 9);

SELECT * FROM TEST;
