-- 1. Pentru fiecare client, sa se afiseze la cate filme de actiune distincte a fost. Daca nu a fost la niciun film de actiunea, se va afisa ”---”.
SELECT C.NAME, NVL(TO_CHAR(COUNT(DISTINCT CASE WHEN UPPER(M.GENRE) = 'ACTION' THEN MSR.ID_MOVIE END)), '---') AS "NUMAR FILME ACTIUNE" 
FROM CLIENTS C
JOIN BOOKINGS B ON B.ID_CLIENT = C.ID_CLIENT
JOIN MOVIE_SCREENING_ROOM MSR ON MSR.ID_SCREENING = B.ID_SCREENING
JOIN MOVIES M ON M.ID_MOVIE = MSR.ID_MOVIE
GROUP BY C.NAME;

-- 2. Sa se afiseze numarul de clienti care au fost la film in sali VIP.
SELECT COUNT(DISTINCT C.ID_CLIENT) AS "NUMAR CLIENTI"
FROM CLIENTS C
JOIN BOOKINGS B ON B.ID_CLIENT = C.ID_CLIENT
JOIN MOVIE_SCREENING_ROOM MSR ON MSR.ID_SCREENING = B.ID_SCREENING
JOIN SCREENING_ROOMS S ON S.ID_ROOM = MSR.ID_ROOM
WHERE UPPER(S.TYPE) = 'VIP';

-- Aici imi afiseaza pentru fiecare client la cate filme a fost
-- SELECT C.NAME, COUNT(C.ID_CLIENT) AS "NUMAR CLIENTI"
-- FROM CLIENTS C
-- JOIN BOOKINGS B ON B.ID_CLIENT = C.ID_CLIENT
-- JOIN MOVIE_SCREENING_ROOM MSR ON MSR.ID_SCREENING = B.ID_SCREENING
-- JOIN SCREENING_ROOMS S ON S.ID_ROOM = MSR.ID_ROOM
-- WHERE UPPER(S.TYPE) = 'VIP'
-- GROUP BY C.NAME;

-- 3. Pentru fiecare film, sa se afiseze incasarile facute in primele 3 saptamani ale lunii aprilie 2024.
SELECT M.NAME, SUM(MSR.TICKET_PRICE * B.NUMBER_TICKETS) AS "INCASARI IN PRIMELE 3 SAPTAMANI ALE LUNII APRILIE 2024"
FROM MOVIES M
JOIN MOVIE_SCREENING_ROOM MSR ON MSR.ID_MOVIE = M.ID_MOVIE
JOIN SCREENING_ROOMS S ON S.ID_ROOM = MSR.ID_ROOM
JOIN BOOKINGS B ON B.ID_SCREENING = MSR.ID_SCREENING
WHERE MSR.SCREENING_DATE BETWEEN TO_DATE('2024-04-01', 'YYYY-MM-DD') AND TO_DATE('2024-04-21', 'YYYY-MM-DD')
GROUP BY M.NAME
ORDER BY "INCASARI IN PRIMELE 3 SAPTAMANI ALE LUNII APRILIE 2024";

