--------------
-- CERINTE: --
--------------

-- 10. Crearea unei secvențe ce va fi utilizată în inserarea înregistrărilor în tabele (punctul 11). 
-- 11. Crearea tabelelor în SQL și inserarea de date coerente în fiecare dintre acestea (minimum 5 înregistrări în fiecare tabel neasociativ; minimum 10 înregistrări în tabelele asociative; maxim 30 de înregistrări în fiecare tabel). 

-------------
-- TABELE: --
-------------

-- UTILIZATOR (#id_utilizator, id_trupa, id_lista, id_cor, nume) 
-- VOCALIST (#id_utilizator, rol) 
-- INSTRUMENTIST (#id_utilizator) 
-- INSTRUMENT (id_instrumentist, denumire) 
-- LISTA (#id_lista, id_cantare, id_utilizator, nume, data_programare, locatie_programare) 
-- CANTARE (#id_cantare, id_autor, id_lista, id_categorie, nume, gama, bpm) 
-- AUTOR (#id_autor, id_cantare, nume, an_debut) 
-- CATEGORIE (id_cantare, denumire) 
-- COR (#id_cor, id_biserica, numar_membrii, id_utilizator) 
-- BISERICA (#id_biserica, nume) 
-- TRUPA (#id_trupa, nume, an_debut, id_utilizator) 
-- PREMIU (#id_premiu, loc_podium) 
-- COMPETITIE (#id_competitie, nume, locatie) 

-- STERGEM VECHILE TABELE
DROP TABLE UTILIZATOR;
DROP TABLE VOCALIST;
DROP TABLE INSTRUMENTIST;
DROP TABLE INSTRUMENT;
DROP TABLE LISTA;
DROP TABLE CANTARE;
DROP TABLE AUTOR;
DROP TABLE CATEGORIE;
DROP TABLE COR;
DROP TABLE BISERICA;
DROP TABLE TRUPA;
DROP TABLE PREMIU;
DROP TABLE COMPETITIE;

-- ASIDE: STERGEM NISTE TABELE DE TEST (MICA OBSERVATIE: SE PARE CA E CASE-SENSITIVE :) )
DROP TABLE test;
DROP TABLE TEST;

-- STERGEM VECHEA SECVENTA
DROP SEQUENCE PROGRAM_SEQUENCE;

-- FACEM O NOUA SECVENTA
CREATE SEQUENCE PROGRAM_SEQUENCE 
START WITH 1 INCREMENT BY 1;
 
---------------------
-- ENTITATE: TRUPA --
---------------------

CREATE TABLE TRUPA (
    ID_TRUPA NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL,
    AN_DEBUT NUMBER NOT NULL
);

INSERT INTO TRUPA (ID_TRUPA, NUME, AN_DEBUT) VALUES
(PROGRAM_SEQUENCE.NEXTVAL, 'NOT AN IDOL', 2012),
(PROGRAM_SEQUENCE.NEXTVAL, 'PROFIDES', 2009),
(PROGRAM_SEQUENCE.NEXTVAL, 'CIRESARII', 2001),
(PROGRAM_SEQUENCE.NEXTVAL, 'CRISTOCENTRIC', 2003),
(PROGRAM_SEQUENCE.NEXTVAL, 'UMAR LA UMAR', 2022),
(PROGRAM_SEQUENCE.NEXTVAL, 'CALATISE PRAISE', 2010),
(PROGRAM_SEQUENCE.NEXTVAL, 'ELEVATION WORSHIP', 2023),
(PROGRAM_SEQUENCE.NEXTVAL, 'BBSO', 20018),
(PROGRAM_SEQUENCE.NEXTVAL, 'TRIBL', 2024),
(PROGRAM_SEQUENCE.NEXTVAL, 'HARVEST ARAD', 2025); -- ID: 1-10

----------------------
-- ENTITATE: PREMIU --
----------------------

CREATE TABLE PREMIU (
    ID_PREMIU NUMBER PRIMARY KEY,
    LOC_PODIUM NUMBER NOT NULL
);

INSERT INTO PREMIU (ID_PREMIU, LOC_PODIUM) VALUES
(PROGRAM_SEQUENCE.NEXTVAL, 3),
(PROGRAM_SEQUENCE.NEXTVAL, 2),
(PROGRAM_SEQUENCE.NEXTVAL, 3),
(PROGRAM_SEQUENCE.NEXTVAL, 1),
(PROGRAM_SEQUENCE.NEXTVAL, 1),
(PROGRAM_SEQUENCE.NEXTVAL, 2),
(PROGRAM_SEQUENCE.NEXTVAL, 2),
(PROGRAM_SEQUENCE.NEXTVAL, 2),
(PROGRAM_SEQUENCE.NEXTVAL, 3),
(PROGRAM_SEQUENCE.NEXTVAL, 1); -- ID: 11-20

--------------------------
-- ENTITATE: COMPETITIE --
--------------------------

CREATE TABLE COMPETITIE (
    ID_COMPETITIE NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL,
    LOCATIE VARCHAR(44) NOT NULL
);

INSERT INTO COMPETITIE (ID_COMPETITIE, NUME, LOCATIE) VALUES
(PROGRAM_SEQUENCE.NEXTVAL, 'VOCEA ROMANIEI', 'BUCURESTI'),
(PROGRAM_SEQUENCE.NEXTVAL, 'ROMANII AU TALENT', 'CLUJ'),
(PROGRAM_SEQUENCE.NEXTVAL, 'TINERI SI CREDINCIOSI', 'BACAU'),
(PROGRAM_SEQUENCE.NEXTVAL, 'X FACTOR', 'MARAMURES'),
(PROGRAM_SEQUENCE.NEXTVAL, 'ROMANII AU TALENT', 'CONSTANTA'),
(PROGRAM_SEQUENCE.NEXTVAL, 'TINERI SI CREDINCIOSI', 'VRANCEA'),
(PROGRAM_SEQUENCE.NEXTVAL, 'X FACTOR', 'ZALAU'),
(PROGRAM_SEQUENCE.NEXTVAL, 'VOCEA ROMANIEI', 'ORADEA'),
(PROGRAM_SEQUENCE.NEXTVAL, 'ROMANII AU TALENT', 'SUCEAVA'),
(PROGRAM_SEQUENCE.NEXTVAL, 'TINERI SI CREDINCIOSI', 'BUCURESTI'); -- ID: 21-30

----------------------------------------------
-- TABEL ASOCIATIV: TRUPA-PREMIU-COMPETITIE --
----------------------------------------------

CREATE TABLE TRUPA_PREMIU_COMPETITIE (
    ID_TRUPA NUMBER,
    ID_PREMIU NUMBER,
    ID_COMPETITIE NUMBER,
    PRIMARY KEY (ID_TRUPA, ID_PREMIU, ID_COMPETITIE),
    FOREIGN KEY (ID_TRUPA) REFERENCES TRUPA (ID_TRUPA),
    FOREIGN KEY (ID_COMPETITIE) REFERENCES COMPETITIE (ID_COMPETITIE),
    FOREIGN KEY (ID_PREMIU) REFERENCES PREMIU (ID_PREMIU)
);

INSERT INTO TRUPA_PREMIU_COMPETITIE (ID_TRUPA, ID_PREMIU, ID_COMPETITIE) VALUES
(1, 11, 21),
(2, 14, 22),
(2, 13, 25),
(2, 18, 22),
(4, 12, 25),
(3, 19, 21),
(4, 17, 22),
(9, 14, 23),
(8, 11, 22),
(4, 18, 27);

---------------------
-- ENTITATE: LISTA --
---------------------

CREATE TABLE LISTA (
    ID_LISTA NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL,
    DATA_PROGRAMARE DATE NOT NULL,
    LOCATIE_PROGRAMARE VARCHAR(44) NOT NULL
);

INSERT INTO LISTA (ID_LISTA, NUME, DATA_PROGRAMARE, LOCATIE_PROGRAMARE, ID_UTILIZATOR) VALUES
(PROGRAM_SEQUENCE.NEXTVAL, 'REPETITII', 2025-05-21, 'VALENII DE MUNTE', 1),
(PROGRAM_SEQUENCE.NEXTVAL, 'KARAOKE', 2025-05-21, 'BISTRITA', 3),
(PROGRAM_SEQUENCE.NEXTVAL, 'FESTIVAL', 2025-05-21, 'CLUJ-NAPOCA', 8),
(PROGRAM_SEQUENCE.NEXTVAL, 'CONCERT', 2025-05-21, 'ARAD', 1),
(PROGRAM_SEQUENCE.NEXTVAL, 'REPETITII', 2025-05-21, 'TIMISOARA', 2),
(PROGRAM_SEQUENCE.NEXTVAL, 'FESTIVAL', 2025-05-21, 'VRANCEA', 8),
(PROGRAM_SEQUENCE.NEXTVAL, 'CONCERT', 2025-05-21, 'ARAD', 4),
(PROGRAM_SEQUENCE.NEXTVAL, 'CONCERT', 2025-05-21, 'VRANCEA', 9),
(PROGRAM_SEQUENCE.NEXTVAL, 'REPETITII', 2025-05-21, 'TULCEA', 1),
(PROGRAM_SEQUENCE.NEXTVAL, 'FESTIVAL', 2025-05-21, 'BACAU', 2); -- ID: 31-40

------------------------
-- ENTITATE: BISERICA --
------------------------

CREATE TABLE BISERICA (
    ID_BISERICA NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL
);

INSERT INTO BISERICA (ID_BISERICA, NUME) VALUES
(PROGRAM_SEQUENCE.NEXT_VAL, 'BETANIA BUCURESTI'),
(PROGRAM_SEQUENCE.NEXT_VAL, 'HARVEST ARAD'),
(PROGRAM_SEQUENCE.NEXT_VAL, 'PROFIDES BUCURESTI'),
(PROGRAM_SEQUENCE.NEXT_VAL, 'BETEL ADJUD'),
(PROGRAM_SEQUENCE.NEXT_VAL, 'VESTEA BUNA BUCURESTI'),
(PROGRAM_SEQUENCE.NEXT_VAL, 'PROFIDES PARIS'),
(PROGRAM_SEQUENCE.NEXT_VAL, 'RENOVATIO'),
(PROGRAM_SEQUENCE.NEXT_VAL, 'BISERICA POGORAREA SFANTULUI DUH TITAN'), -- 38 < 44 SE INCADREAZA IN LIMITA :)
(PROGRAM_SEQUENCE.NEXT_VAL, 'BISERICA PROFIDES LUPENI'),
(PROGRAM_SEQUENCE.NEXT_VAL, 'BISERICA BETEL COMANESTI'); -- ID: 41-50

-------------------
-- ENTITATE: COR --
-------------------

CREATE TABLE COR (
    ID_COR NUMBER PRIMARY KEY,
    NUMAR_MEMBRII NUMBER NOT NULL,
    FOREIGN KEY (ID_BISERICA) REFERENCES BISERICA (ID_BISERICA)
);

INSERT INTO COR (ID_COR, NUMAR_MEMBRII, ID_BISERICA) VALUES
(PROGRAM_SEQUENCE.NEXTVAL, 800, 41),
(PROGRAM_SEQUENCE.NEXTVAL, 100, 49),
(PROGRAM_SEQUENCE.NEXTVAL, 400, 42),
(PROGRAM_SEQUENCE.NEXTVAL, 80, 41),
(PROGRAM_SEQUENCE.NEXTVAL, 40, 48),
(PROGRAM_SEQUENCE.NEXTVAL, 12OO, 45),
(PROGRAM_SEQUENCE.NEXTVAL, 2000, 48),
(PROGRAM_SEQUENCE.NEXTVAL, 18, 41),
(PROGRAM_SEQUENCE.NEXTVAL, 20000, 49),
(PROGRAM_SEQUENCE.NEXTVAL, 82, 50); -- ID: 51-60

--------------------------
-- ENTITATE: UTILIZATOR --
--------------------------

CREATE TABLE UTILIZATOR (
    ID_UTILIZATOR NUMBER PRIMARY KEY,
    NUME VARCHAR2(44) NOT NULL,
    FOREIGN KEY (ID_TRUPA) REFERENCES TRUPA(ID_TRUPA),
    FOREIGN KEY (ID_LISTA) REFERENCES LISTA(ID_LISTA),
    FOREIGN KEY (ID_COR) REFERENCES COR(ID_COR)
);

INSERT INTO UTILIZATOR (ID_UTILIZATOR, NUME, ID_TRUPA, ID_LISTA, ID_COR) VALUES 
(PROGRAM_SEQUENCE.NEXTVAL, 'ANA', 1, 31, 51),
(PROGRAM_SEQUENCE.NEXTVAL, 'BOGDAN', 7, 34, 54),
(PROGRAM_SEQUENCE.NEXTVAL, 'MIRCEA', 9, 39, 52),
(PROGRAM_SEQUENCE.NEXTVAL, 'MARIA', 4, 38, 58),
(PROGRAM_SEQUENCE.NEXTVAL, 'IOANA', 3, 31, 57),
(PROGRAM_SEQUENCE.NEXTVAL, 'CARLOS'9, , 31, 55),
(PROGRAM_SEQUENCE.NEXTVAL, 'TONI', 4, 37, 54),
(PROGRAM_SEQUENCE.NEXTVAL, 'VLAD', 8, 34, 58),
(PROGRAM_SEQUENCE.NEXTVAL, 'DIANA', 2, 33, 53),
(PROGRAM_SEQUENCE.NEXTVAL, 'FLORENTINA', 10, 40, 60); -- ID: 61-70

------------------------
-- ENTITATE: VOCALIST --
------------------------

CREATE TABLE VOCALIST (
    FOREIGN KEY (ID_UTILIZATOR) REFERENCES UTILIZATOR (ID_UTILIZATOR),
    ROL VARCHAR(44) NOT NULL
);

INSERT INTO VOCALIST (ID_UTILIZATOR, ROL) VALUES
(61, 'SOPRANO'),
(63, 'BASS'),
(68, 'SOPRANO'),
(62, 'TENOR'),
(63, 'TENOR'),
(67, 'BASS'),
(61, 'SOPRANO'),
(65, 'BASS'),
(61, 'BASS'),
(70, 'TENOR');

-----------------------------
-- ENTITATE: INSTRUMENTIST --
-----------------------------

CREATE TABLE INSTRUMENTIST (
    FOREIGN KEY (ID_UTILIZATOR) REFERENCES UTILIZATOR (ID_UTILIZATOR)
);

INSERT INTO INSTRUMENTIST (ID_UTILIZATOR) VALUES
(61),
(62),
(68),
(64),
(68),
(63),
(64),
(61),
(68),
(70);

--------------------------
-- ENTITATE: INSTRUMENT --
--------------------------

CREATE TABLE INSTRUMENT (
    FOREIGN KEY ID_UTILIZATOR REFERENCES UTILIZATOR (ID_UTILIZATOR),
    DENUMIRE VARCHAR(44) NOT NULL
);

INSERT INTO INSTRUMENT (ID_UTILIZATOR, DENUMIRE) VALUES
(61, 'PIAN'),
(68, 'CHITARA'),
(64, 'MANDOLINA'),
(68, 'TOBE'),
(63, 'CHITARA ELECTRICA'),
(62, 'CHITARA BASS'),
(67, 'PIAN'),
(62, 'TOBE'),
(65, 'MANDOLINA'),
(70, 'VIOARA');

-----------------------
-- ENTITATE: CANTARE --
-----------------------

CREATE TABLE CANTARE (
    ID_CANTARE NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL,
    GAMA VARCHAR(4) NOT NULL,
    BPM NUMBER NOT NULL,
    FOREIGN KEY ID_LISTA REFERENCES LISTA (ID_LISTA)
);

INSERT INTO CANTARE (ID_CANTARE, NUME, GAMA, BPM, ID_LISTA) VALUES
(PROGRAM_SEQUENCE.NEXTVAL, 'DOMNUL MINUNILOR', 'G#', 120, 31),
(PROGRAM_SEQUENCE.NEXTVAL, 'ACEASTA E ZIUA DOMNULUI', 'C', 70, 37),
(PROGRAM_SEQUENCE.NEXTVAL, 'LUCRURI NOI', 'F', 100, 34),
(PROGRAM_SEQUENCE.NEXTVAL, 'ANCORA', 'D', 110, 32),
(PROGRAM_SEQUENCE.NEXTVAL, 'ZI DE ZI', 'G', 120, 39),
(PROGRAM_SEQUENCE.NEXTVAL, 'DOMNUL STEAGUL MEU', 'D#', 90, 31),
(PROGRAM_SEQUENCE.NEXTVAL, 'ESTI UNIC', 'A#', 50, 36),
(PROGRAM_SEQUENCE.NEXTVAL, 'DUMNEZEUL PUTERNIC', 'C', 70, 33),
(PROGRAM_SEQUENCE.NEXTVAL, 'CREDINCIOS', 'E', 90, 34),
(PROGRAM_SEQUENCE.NEXTVAL, 'DUMNEZEU E TARIA MEA', 'A#', 40, 40); -- ID: 71-80

---------------------
-- ENTITATE: AUTOR --
---------------------

CREATE TABLE AUTOR (
    ID_AUTOR NUMBER PRIMARY KEY,
    NUME VARCHAR(44) NOT NULL,
    AN_DEBUT NUMBER NOT NULL,
    FOREIGN KEY (ID_CANTARE) REFERENCES CANTARE (ID_CANTARE)
);

INSERT INTO AUTOR (ID_AUTOR, NUME, AN_DEBUT, ID_CANTARE) VALUES
(PROGRAM_SEQUENCE.NEXTVAL, 'SUNNY TRANCA', 2005, 71),
(PROGRAM_SEQUENCE.NEXTVAL, 'TONI BERBECE', 2008, 79),
(PROGRAM_SEQUENCE.NEXTVAL, 'VALI TRANCA', 2024, 75),
(PROGRAM_SEQUENCE.NEXTVAL, 'MIRIAM POPESCU', 20012, 71),
(PROGRAM_SEQUENCE.NEXTVAL, 'ANCA BAN', 2003, 74),
(PROGRAM_SEQUENCE.NEXTVAL, 'ALIN JIVAN', 2004, 77),
(PROGRAM_SEQUENCE.NEXTVAL, 'FLORINA JIVAN', 2004, 72),
(PROGRAM_SEQUENCE.NEXTVAL, 'SUNNY TRANCA', 2005, 79),
(PROGRAM_SEQUENCE.NEXTVAL, 'MIRIAM POPESCU', 2012, 73),
(PROGRAM_SEQUENCE.NEXTVAL, 'TONI BERBECE', 2008, 80); -- ID: 81-90

-------------------------
-- ENTITATE: CATEGORIE --
-------------------------

CREATE TABLE CATEGORIE (
    FOREIGN KEY (ID_CANTARE) REFERENCES CANTARE (ID_CANTARE),
    DENUMIRE VARCHAR(44) NOT NULL
);

INSERT INTO CATEGORIE (ID_CANTARE, DENUMIRE) VALUES
(71, 'JAZZ'),
(78, 'POP'),
(72, 'ROCK'),
(73, 'IMN'),
(78, 'BISERICEASCA'),
(77, 'LAUTAREASCA'),
(79, 'POP'),
(75, 'ROCK'),
(73, 'JAZZ'),
(80, 'POP');
